---
resources:
  - name: repository
    type: git
    check_every: 24h
    icon: github-circle
    webhook_token: ((webhook_token-concourse))
    source:
      uri: https://github.com/ONSdigital/concourse-deploy
      branch: lu_3662_pull_request

jobs:
  - name: serverless-deploy
    plan:
      - get: repository
        trigger: true
        version: every

      - task: serverless-aws
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: 014669633018.dkr.ecr.eu-west-2.amazonaws.com/results-cicd
              aws_access_key_id: ((ecr-svcaccount.api-key))
              aws_secret_access_key: ((ecr-svcaccount.api-secret))
          params:
            AWS_ACCESS_KEY_ID: ((serverless-access-key.AWS_ACCESS_KEY_ID))
            AWS_SECRET_ACCESS_KEY: ((serverless-access-key.AWS_SECRET_ACCESS_KEY))
            SLS_DEBUG: 1
          inputs:
            - name: repository
          run:
            path: repository/serverless.sh
