---
resources:
  - name: repository
    type: git
    check_every: 24h
    icon: github-circle
    webhook_token: ((webhook_token-concourse))
    source:
      uri: https://github.com/ONSdigital/concourse-deploy
      branch: master

jobs:
  - name: pipeline-deploy
    plan:
      - get: repository
        trigger: true
      - task: set-pipelines
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: 014669633018.dkr.ecr.eu-west-2.amazonaws.com/results-cicd
              aws_access_key_id: ((ecr-svcaccount.api-key))
              aws_secret_access_key: ((ecr-svcaccount.api-secret))
          inputs:
            - name: repository
          run:
            path: repository/set-pipeline.sh
