---
resources:
  - name: git-Repository
    type: git
    source:
      uri: https://github.com/thomashenson/concourse-deploy-test
      branch: master

jobs:
  - name: deploy-app
    public: true
    serial: true
    plan:
      - get: git-repository
        trigger: true
      - task: aws-tests
        config:
          platform: linux
          image_resource:
            type: docker-image
            source: {repository: thomashenson/docker-concourse}
          inputs:
            - name: git-repository

          run:
            path: git-repository/scripts/aws-test.sh

  - name: serverless-deploy
    public: true
    serial: true
    plan:
      - get: git-repository
      - task: serverless-aws
        config:
          platform: linux
          image_resource:
            type: docker-image
            source: {repository: thomashenson/docker-concourse}
          inputs:
            - name: git-repository

          run:
            path: git-repository/scripts/serverless.sh