---
resources:
  - name: GIT-repository
    type: git
    source:
      uri: https://github.com/thomashenson/concourse-deploy-test
      branch: master

jobs:
  - name: linting-and-tests
    public: true
    serial: true
    plan:
      - get: GIT-repository
        trigger: true
      - task: aws-tests
        config:
          platform: linux
          image_resource:
            type: docker-image
            source: {repository: thomashenson/docker-concourse, tag: test}
          inputs:
            - name: GIT-repository
          run:
            path: GIT-repository/scripts/aws-test.sh

  - name: serverless-deploy
    public: true
    plan:
      - get: GIT-repository
        passed: [linting-and-tests]
        trigger: true
      - task: serverless-aws
        config:
          platform: linux
          image_resource:
            type: docker-image
            source: {repository: thomashenson/docker-concourse, tag: test}
          inputs:
            - name: GIT-repository
          run:
            path: GIT-repository/scripts/serverless.sh