---
resource_types:
  - name: pull-request
    type: docker-image
    source:
      repository: teliaoss/github-pr-resource

resources:
  - name: repository
    type: pull-request
    check_every: 24h
    webhook_token: ((webhook_token-concourse))
    icon: github-circle
    source:
      repository: ONSdigital/es-concourse-deploy
      access_token: ((git_access_token))

#  - name: base-python-image
#    type: docker-image
#    icon: language-python
#    source:
#      repository: python
#      tag: 3.7-slim
#

  - name: ecr-image-upload
    type: docker-image
    icon: docker
    source:
      repository: 014669633018.dkr.ecr.eu-west-2.amazonaws.com/results-cicd
      aws_access_key_id: ((ecr-svcaccount.api-key))
      aws_secret_access_key: ((ecr-svcaccount.api-secret))

jobs:
  - name: installing dependencies
    serial: true
    plan:

      - get: repository
        trigger: true

      - get: ecr-image-upload
        params:
          save: true

      - put: ecr-image-upload
        params:
          load_base: ecr-image-upload
          build: repository

      - task: run
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: 014669633018.dkr.ecr.eu-west-2.amazonaws.com/results-cicd
              aws_access_key_id: ((ecr-svcaccount.api-key))
              aws_secret_access_key: ((ecr-svcaccount.api-secret))
          inputs:
            - name: repository
          run:
            path: repository/install-dependencies.sh

  - name: linting & tests
    plan:

      - get: repository
        trigger: true
        passed: [installing dependencies]
        version: every

      - put: repository
        params:
          path: repository
          status: pending

      - in_parallel:
        - task: aws-tests
          config:
            platform: linux
            image_resource:
              type: docker-image
              source:
                repository: 014669633018.dkr.ecr.eu-west-2.amazonaws.com/results-cicd
                aws_access_key_id: ((ecr-svcaccount.api-key))
                aws_secret_access_key: ((ecr-svcaccount.api-secret))
            inputs:
              - name: repository
            run:
              path: repository/aws-test.sh
          on_failure:
            put: repository
            params:
              path: repository
              status: failure
              description: Failing tests are present

        - task: flake8
          config:
            platform: linux
            image_resource:
              type: docker-image
              source:
                repository: 014669633018.dkr.ecr.eu-west-2.amazonaws.com/results-cicd
                aws_access_key_id: ((ecr-svcaccount.api-key))
                aws_secret_access_key: ((ecr-svcaccount.api-secret))
            inputs:
              - name: repository
            run:
              path: repository/flake8.sh
          on_failure:
            put: repository
            params:
              path: repository
              status: failure
              description: Code standards are not met