---
resource_types:
  - name: pull-request
    type: docker-image
    source:
      repository: teliaoss/github-pr-resource

resources:
  - name: rebuild-repository
    type: pull-request
    check_every: 24h
    webhook_token: ((webhook_token-concourse))
    icon: github-circle
    source:
      paths:
        - dev-requirements.txt
      repository: ONSdigital/((repo-name))
      access_token: ((git_access_token))


  - name: pr-repository
    type: pull-request
    check_every: 24h
    webhook_token: ((webhook_token-concourse))
    icon: github-circle
    source:
      repository: ONSdigital/((repo-name))
      access_token: ((git_access_token))

  - name: code-repository
    type: git
    icon: github-circle
    source:
      uri: https://github.com/ONSdigital/es-concourse-deploy.git

  - name: base-python-image
    type: docker-image
    icon: language-python
    source:
      repository: python
      tag: 3.7-slim

  - name: ecr-image-upload
    type: docker-image
    icon: docker
    source:
      repository: 014669633018.dkr.ecr.eu-west-2.amazonaws.com/results-cicd
      aws_access_key_id: ((ecr-svcaccount.api-key))
      aws_secret_access_key: ((ecr-svcaccount.api-secret))

jobs:
  - name: rebuildonchange
    serial: true
    serial_groups: [rebuild]
    plan:
    - in_parallel:
      - get: rebuild-repository
        trigger: true
      - get: code-repository

      - get: base-python-image
        params:
          cache: false
          save: true
    - put: ecr-image-upload
      params:
        save: true
        load_base: base-python-image
        build: code-repository
        cache: true
        cache_tag: latest
      get_params:
        skip_download: true

  - name: linting & tests
    serial_groups: [rebuild]
    plan:
    - in_parallel:
      - get: pr-repository
        trigger: true
        version: every
      - get: ecr-image-upload
        params:
          load: image
          cache: true
          save: true
    - put: pr-repository
      params:
        path: pr-repository
        status: success


    - in_parallel:
      - task: aws-tests
        config:
          caches: 
          - path: image
          platform: linux
          image_resource:
            type: docker-image
            params:
              cache: true
              load: image
            source:
              repository: 014669633018.dkr.ecr.eu-west-2.amazonaws.com/results-cicd
              aws_access_key_id: ((ecr-svcaccount.api-key))
              aws_secret_access_key: ((ecr-svcaccount.api-secret))
          inputs:
            - name: pr-repository
            - name: ecr-image-upload
          run:
            path: sh
            args:
              - -exc
              - |
                cd pr-repository
                PYTHONPATH=$(pwd) pytest
        on_failure:
          put: pr-repository
          params:
            path: pr-repository
            status: failure
            description: Failing tests are present

      - task: flake8
        config:
          caches: 
          - path: image
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: 014669633018.dkr.ecr.eu-west-2.amazonaws.com/results-cicd
              aws_access_key_id: ((ecr-svcaccount.api-key))
              aws_secret_access_key: ((ecr-svcaccount.api-secret))
          inputs:
            - name: pr-repository
          run:
            path: sh
            args:
              - -exc
              - |
                flake8 $(pwd)
        on_failure:
          put: pr-repository
          params:
            path: pr-repository
            status: failure
            description: Code standards are not met
      on_failure:
          put: pr-repository
          params:
            path: pr-repository
            status: failure
            description: Both linting and pytest have failed.

