---
resources:
  - name: GIT-repository
    type: git
    source:
      uri: https://github.com/thomashenson/concourse-deploy-test
      branch: serverless

  - name: Python-container
    type: docker-image
    source:
      username: ((docker-username))
      password: ((docker-password))
      repository: ((docker-username))/docker-concourse

jobs:
  - name: installing-dependencies
    serial: true
    plan:
      - get: GIT-repository
        trigger: true
      - put: Python-container
        params:
          build: GIT-repository
      # - task: run
      #   config:
      #     platform: linux
      #     image_resource:
      #       type: docker-image
      #       source:
      #         repository: ((docker-username))/docker-concourse
      #     inputs:
      #       - name: GIT-repository
      #     run:
      #       path: GIT-repository/docker/install-dependencies.sh

  - name: linting-and-tests
    plan:
      - get: GIT-repository
        trigger: true
        passed: [installing-dependencies]
      - task: aws-tests
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: ((docker-username))/docker-concourse
          inputs:
            - name: GIT-repository
          run:
            path: GIT-repository/aws-test.sh

  - name: serverless-deploy
    plan:
      - get: GIT-repository
        trigger: true
        passed: [linting-and-tests]
      - task: serverless-aws
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: ((docker-username))/docker-concourse
          params:
            AWS_ACCESS_KEY_ID: ((serverless-access-key.AWS_ACCESS_KEY_ID))
            AWS_SECRET_ACCESS_KEY: ((serverless-access-key.AWS_SECRET_ACCESS_KEY))
          inputs:
            - name: GIT-repository
          run:
            path: GIT-repository/serverless.sh