---
resources:
  - name: GIT-repository
    type: git
    source:
      uri: https://github.com/thomashenson/concourse-deploy-test
      branch: parallel

jobs:
  - name: linting-and-tests
    serial: true
    plan:
      - get: GIT-repository
        trigger: true
      - in_parallel:
        - task: aws-tests
          config:
            platform: linux
            image_resource:
              type: docker-image
              source:
                repository: ((docker-username))/docker-concourse
            inputs:
              - name: GIT-repository
            run:
              path: GIT-repository/aws-test.sh
        - task: flake8
          config:
            platform: linux
            image_resource:
              type: docker-image
              source:
                repository: ((docker-username))/docker-concourse
            inputs:
              - name: GIT-repository
            run:
              path: GIT-repository/flake8.sh

  - name: serverless-deploy
    plan:
      - get: GIT-repository
        trigger: true
        passed: [linting-and-tests]
      - task: serverless-aws
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: ((docker-username))/docker-concourse
          params:
            AWS_ACCESS_KEY_ID: ((serverless-access-key.AWS_ACCESS_KEY_ID))
            AWS_SECRET_ACCESS_KEY: ((serverless-access-key.AWS_SECRET_ACCESS_KEY))
            SLS_DEBUG: 1
          inputs:
            - name: GIT-repository
          run:
            path: GIT-repository/serverless.sh