---
resources:
  - name: GIT-repository
    type: git
    source:
      uri: https://github.com/thomashenson/concourse-deploy-test
      branch: test_stage

  - name: Python-container
    type: docker-image
    source:
      email: thomasjameshenson@gmail.com
      username: thomashenson
      password: Volkswagen32
      repository: thomashenson/docker-concourse

jobs:
  - name: installing-dependencies
    serial: true
    plan:
      - get: GIT-repository
        trigger: true
      - put: Python-container
        params:
          build: GIT-repository
      - task: run
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: thomashenson/docker-concourse
          inputs:
            - name: GIT-repository
          run:
            path: GIT-repository/docker/install-dependencies.sh

  - name: linting-and-tests
    plan:
      - get: GIT-repository
        trigger: true
        passed: [installing-dependencies]
      - get: Python-container
        trigger: true
        passed: [installing-dependencies]
      - task: aws-tests
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: thomashenson/docker-concourse
          inputs:
            - name: GIT-repository
          run:
            path: GIT-repository/docker/aws-test.sh

  - name: serverless-deploy
    plan:
      - get: GIT-repository
        passed: [linting-and-tests]
        trigger: true
      - get: Python-container
      - task: serverless-aws
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: thomashenson/docker-concourse
              tag: test
          inputs:
            - name: GIT-repository
          run:
            path: GIT-repository/docker/serverless.sh